<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<ClangFormatRid Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</ClangFormatRid>
		<ClangFormatRid Condition="'$(ClangFormatRid)' == ''">$(NETCoreSdkRuntimeIdentifier)</ClangFormatRid>
	</PropertyGroup>

	<ItemGroup Condition="'$(ClangFormatRid)' == 'win-x64'">
		<Content Include="tools\clang-format-win-x64.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>tools\clang-format.exe</Link>
		</Content>
	</ItemGroup>

	<ItemGroup Condition="'$(ClangFormatRid)' == 'win-arm64'">
		<Content Include="tools\clang-format-win-arm64.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>tools\clang-format.exe</Link>
		</Content>
	</ItemGroup>

	<ItemGroup Condition="'$(ClangFormatRid)' == 'linux-x64'">
		<Content Include="tools\clang-format-linux-x64">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>tools\clang-format</Link>
		</Content>
	</ItemGroup>

	<ItemGroup Condition="'$(ClangFormatRid)' == 'linux-arm64'">
		<Content Include="tools\clang-format-linux-arm64">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>tools\clang-format</Link>
		</Content>
	</ItemGroup>


</Project>
